In [26]:
import pandas as pd
import numpy as np

In [27]:
df = pd.read_excel(r"C:\Users\DELL\Documents\Churn Prediction\data\raw\Telco_customer_churn.xlsx"
)

In [28]:
df.shape

(7043, 33)

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   str
 3   State              7043 non-null   str
 4   City               7043 non-null   str
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   str
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   str
 10  Senior Citizen     7043 non-null   str
 11  Partner            7043 non-null   str
 12  Dependents         7043 non-null   str
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   str
 15  Multiple Lines     7043 non-null   str
 16  Internet Service   7043 non-null   str
 17  Online Security    7043 non-null   str
 18  Online Backup      7043 non-null   str
 19  Device Protection  7043 non-null   str
 20  Tech Support       7043 non-null   str
 21  Streaming TV       7043 non-null   str
 22  Streaming Movies   7043 non-null   str
 23  Contract           7043 non-null   str
 24  Paperless Billing  7043 non-null   str
 25  Payment Method     7043 non-null   str
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   str
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   str
dtypes: float64(3), int64(6), object(1), str(23)
memory usage: 1.8+ MB

In [30]:
pd.set_option("display.max_columns", None)

df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [31]:
for col in["Count","Country","State"]:
    print(col,df[col].value_counts())

Count Count
1    7043
Name: count, dtype: int64
Country Country
United States    7043
Name: count, dtype: int64
State State
California    7043
Name: count, dtype: int64

In [32]:
df[["City", "Zip Code", "Lat Long", "Latitude", "Longitude"]].nunique()

City         1129
Zip Code     1652
Lat Long     1652
Latitude     1652
Longitude    1651
dtype: int64

- We are dropping few columns as they are not important.

In [33]:
geo_cols = [
    "City",
    "Zip Code",
    "Lat Long",
    "Latitude",
    "Longitude"
]

df = df.drop(columns=geo_cols)

In [34]:
df = df.drop(["Country","State","Count"],axis=1)

In [35]:
df.head()

,CustomerID,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,Male,No,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,Female,No,No,Yes,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,Female,No,No,Yes,8,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,Female,No,Yes,Yes,28,Yes,Yes,Fiber optic,No,No,Yes,Yes,Yes,Yes,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,Male,No,No,Yes,49,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

- After dropping unimportant columns the shape is:

In [36]:
df.shape

(7043, 25)

- Let's check TotalCharges column as this is very important one

In [37]:
df[df["Total Charges"].astype(str).str.strip() == ""]

,CustomerID,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,Multiple Lines,Internet Service,Online Security,Online Backup,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
2234,4472-LVYGI,Female,No,Yes,No,0,No,No phone service,DSL,Yes,No,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No,0,36,2578,NaN
2438,3115-CZMZD,Male,No,No,No,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No,0,68,5504,NaN
2568,5709-LVOEQ,Female,No,Yes,No,0,Yes,No,DSL,Yes,Yes,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No,0,45,2048,NaN
2667,4367-NUYAO,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No,0,48,4950,NaN
2856,1371-DWPAZ,Female,No,Yes,No,0,No,No phone service,DSL,Yes,Yes,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No,0,30,4740,NaN
4331,7644-OMVMY,Male,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,,No,0,53,2019,NaN
4687,3213-VVOLG,Male,No,Yes,Yes,0,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,,No,0,49,2299,NaN
5104,2520-SGTTA,Female,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,,No,0,27,3763,NaN
5719,2923-ARZLG,Male,No,Yes,Yes,0,Yes,No,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,,No,0,69,4890,NaN
6772,4075-WKNIU,Female,No,Yes,Yes,0,Yes,Yes,DSL,No,Yes,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,,No,0,44,2342,NaN
6840,2775-SEFEE,Male,No,No,Yes,0,Yes,Yes,DSL,Yes,Yes,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,,No,0,65,5188,NaN

In [38]:
df["Total Charges"] = df["Total Charges"].replace(" ",pd.NA)

In [39]:
df["Total Charges"].isnull().sum()

np.int64(11)

In [40]:
df.loc[
    df["Total Charges"].isna(),
    ["Tenure Months", "Monthly Charges", "Churn Label"] #To see those columns(tenure months,monthly charges,churn label) have null "total charges".
    ]

      Tenure Months  Monthly Charges Churn Label
2234              0            52.55          No
2438              0            20.25          No
2568              0            80.85          No
2667              0            25.75          No
2856              0            56.05          No
4331              0            19.85          No
4687              0            25.35          No
5104              0            20.00          No
5719              0            19.70          No
6772              0            73.35          No
6840              0            61.90          No

In [41]:
df["Total Charges"] = df["Total Charges"].fillna(0) #Fill them with 0 because the customer's are newly joined.

In [42]:
df["Total Charges"].isna().sum()

np.int64(0)

In [43]:
df.isnull().sum().sum()

np.int64(5174)

In [44]:
df.duplicated().sum()

np.int64(0)

- **CHURN REASON:** It is very important column for RAG and LLM for later.
But it contains 5,174 missing values which is timewaste if we fill them or encode, because we don't neccessarily need this column to train our model. So we keep seperate this n our original dataset (df) and copy this to "df_model", and when we train model we drop this from feature variable [X].

In [23]:
df_model = df.copy()

In [24]:
df_model.to_csv(

    "../data/preprocessed/churn_cleaned.csv",

    index=False

)

In [ ]:
cols_drop = ['Churn Reason','']